# Generated by Django 5.2.1 on 2025-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_post_image_trend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="trend",
            name="slug",
            field=models.CharField(max_length=150),
        ),
    ]
